# Generated by Django 5.2.17 on 2026-09-19 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('contract_file', models.CharField(blank=True, help_text='Caminho do arquivo do contrato (ex: PDF).', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='tasktrack.usermodel')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
