# Generated by Django 5.2.17 on 2026-09-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0003_ensure_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tasktrack.projectmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='tasktrack.usermodel')),
            ],
            options={
                'db_table': 'project_memberships',
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member')],
            },
        ),
    ]
