# Generated by Django 5.2.17 on 2026-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0005_project_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MEMBER', 'MEMBER'), ('DEVELOPER', 'DEVELOPER'), ('TEST', 'TEST'), ('MANAGER', 'MANAGER'), ('PRODUCT_OWNER', 'PRODUCT_OWNER')], default='MEMBER', max_length=20),
        ),
    ]
