# Generated by Django 5.2.17 on 2026-09-20 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0006_alter_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='github_url',
            field=models.CharField(blank=True, help_text='URL relativa a esta tarefa no GitHub (issue, PR, etc)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TaskHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task_changes', to='tasktrack.usermodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasktrack.taskmodel')),
            ],
            options={
                'db_table': 'task_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
