# Generated by Django 5.2.17 on 2026-09-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0007_taskmodel_github_url_taskhistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
