# Generated by Django 5.2.17 on 2026-09-23 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0008_alter_taskmodel_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('req_type', models.CharField(choices=[('FUNCTIONAL', 'FUNCTIONAL'), ('NON_FUNCTIONAL', 'NON_FUNCTIONAL'), ('BUSINESS_RULE', 'BUSINESS_RULE'), ('TECHNICAL_CONSTRAINT', 'TECHNICAL_CONSTRAINT')], default='FUNCTIONAL', max_length=25)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('APPROVED', 'APPROVED'), ('IMPLEMENTED', 'IMPLEMENTED'), ('DEPRECATED', 'DEPRECATED')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'requirements',
            },
        ),
        migrations.CreateModel(
            name='RequirementTaskLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='tasktrack.requirementmodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='tasktrack.taskmodel')),
            ],
            options={
                'db_table': 'requirement_task_links',
                'constraints': [models.UniqueConstraint(fields=('requirement', 'task'), name='unique_requirement_task')],
            },
        ),
    ]
