# Generated by Django 5.2.17 on 2026-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0009_requirementmodel_requirementtasklinkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierSequenceModel',
            fields=[
                ('prefix', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'identifier_sequences',
            },
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='display_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='display_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='requirementmodel',
            name='display_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='display_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
