# Generated by Django 5.2.17 on 2026-09-24 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0011_backfill_display_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='ActorRequirementLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='tasktrack.actormodel')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_links', to='tasktrack.requirementmodel')),
            ],
            options={
                'db_table': 'actor_requirement_links',
                'constraints': [models.UniqueConstraint(fields=('actor', 'requirement'), name='unique_actor_requirement')],
            },
        ),
    ]
