# Generated by Django 5.2.17 on 2026-09-25 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0012_add_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actormodel',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='tasktrack.contractmodel'),
        ),
        migrations.AddField(
            model_name='requirementmodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tasktrack.projectmodel'),
        ),
    ]
