from django.urls import path
from .views import (
    contracts_view,
    home_view,
    login_view,
    logout_view,
    project_tasks_view,
    projects_view,
    task_status_view,
    task_view,
    web_create_contract_view,
    web_create_project_view,
    web_create_task_view,
    web_create_user_view,
    web_update_contract_status_view,
    web_update_project_status_view,
    web_update_project_team_view,
    web_update_task_status_view,
    web_update_task_view,
    web_delete_task_view,
)

urlpatterns = [
    # Web UI (MVT)
    path("login", login_view, name="login"),
    path("logout", logout_view, name="logout"),
    path("", home_view, name="home"),
    path("web/contracts", web_create_contract_view, name="web_create_contract"),
    path("web/projects", web_create_project_view, name="web_create_project"),
    path("web/contracts/<str:contract_id>/status", web_update_contract_status_view, name="web_update_contract_status"),
    path("web/projects/<str:project_id>/status", web_update_project_status_view, name="web_update_project_status"),
    path("web/projects/<str:project_id>/team", web_update_project_team_view, name="web_update_project_team"),
    path("web/tasks", web_create_task_view, name="web_create_task"),
    path("web/tasks/<str:task_id>/status", web_update_task_status_view, name="web_update_task_status"),
    path("web/tasks/<str:task_id>/delete", web_delete_task_view, name="web_delete_task"),
    path("web/tasks/<str:task_id>", web_update_task_view, name="web_update_task"),
    path("web/users", web_create_user_view, name="web_create_user"),

    # REST API Endpoints (v1)
    path("api/v1/contracts", contracts_view, name="create_contract"),
    path("api/v1/contracts/", contracts_view, name="create_contract_slash"),
    path("api/v1/projects", projects_view, name="create_project"),
    path("api/v1/projects/", projects_view, name="create_project_slash"),
    path("api/v1/projects/<str:project_id>/tasks", project_tasks_view, name="create_task"),
    path("api/v1/projects/<str:project_id>/tasks/", project_tasks_view, name="create_task_slash"),
    path("api/v1/tasks/<str:task_id>/status", task_status_view, name="update_task_status"),
    path("api/v1/tasks/<str:task_id>/status/", task_status_view, name="update_task_status_slash"),
    path("api/v1/tasks/<str:task_id>", task_view, name="update_delete_task"),
    path("api/v1/tasks/<str:task_id>/", task_view, name="update_delete_task_slash"),
]
